# Site
repository: bsp3ars/bsp3ars.github.io
# favicon: images/favicon.ico

# Personal info
name: Brandon Spears
title: Computer Science Student
email: bsp3ars@gmail.com
website: bsp3ars.github.io

# Social links
github_username:  bsp3ars
instagram_username: bsp3ars
linkedin_username: brandon-spears

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brandon and I'm a third year Computer Science student at the University of Cincinnati. I am enthusiastic about software development and learning about new things. I am currently looking for a co-op for the Spring of 2020, so please contact me if I fit the criteria for a position at your company.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in development and engineering some of my other interests and hobbies are:
   - Video Games
   - PC Building
   - Cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag